appbascer/config/routes.rb
Rails.application.routes.draw do
  resources :registro_de_residuos
  resources :users
  get 'welcome/index'
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

appbascer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

appbascer/app/models/registro_de_residuo.rb
class RegistroDeResiduo < ApplicationRecord
end

appbascer/app/models/user.rb
class User < ApplicationRecord
end

appbascer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

appbascer/app/controllers/registro_de_residuos_controller.rb
class RegistroDeResiduosController < ApplicationController
  before_action :set_registro_de_residuo, only: [:show, :edit, :update, :destroy]

  # GET /registro_de_residuos
  # GET /registro_de_residuos.json
  def index
    @registro_de_residuos = RegistroDeResiduo.all
  end

  # GET /registro_de_residuos/1
  # GET /registro_de_residuos/1.json
  def show
  end

  # GET /registro_de_residuos/new
  def new
    @registro_de_residuo = RegistroDeResiduo.new
  end

  # GET /registro_de_residuos/1/edit
  def edit
  end

  # POST /registro_de_residuos
  # POST /registro_de_residuos.json
  def create
    @registro_de_residuo = RegistroDeResiduo.new(registro_de_residuo_params)

    respond_to do |format|
      if @registro_de_residuo.save
        format.html { redirect_to @registro_de_residuo, notice: 'Registro de residuo was successfully created.' }
        format.json { render :show, status: :created, location: @registro_de_residuo }
      else
        format.html { render :new }
        format.json { render json: @registro_de_residuo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registro_de_residuos/1
  # PATCH/PUT /registro_de_residuos/1.json
  def update
    respond_to do |format|
      if @registro_de_residuo.update(registro_de_residuo_params)
        format.html { redirect_to @registro_de_residuo, notice: 'Registro de residuo was successfully updated.' }
        format.json { render :show, status: :ok, location: @registro_de_residuo }
      else
        format.html { render :edit }
        format.json { render json: @registro_de_residuo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registro_de_residuos/1
  # DELETE /registro_de_residuos/1.json
  def destroy
    @registro_de_residuo.destroy
    respond_to do |format|
      format.html { redirect_to registro_de_residuos_url, notice: 'Registro de residuo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro_de_residuo
      @registro_de_residuo = RegistroDeResiduo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_de_residuo_params
      params.require(:registro_de_residuo).permit(:fecha, :tipo, :contenedor, :telefono)
    end
end

appbascer/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

appbascer/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

appbascer/app/helpers/application_helper.rb
module ApplicationHelper
end

appbascer/app/helpers/registro_de_residuos_helper.rb
module RegistroDeResiduosHelper
end

appbascer/app/helpers/users_helper.rb
module UsersHelper
end

appbascer/app/helpers/welcome_helper.rb
module WelcomeHelper
end

appbascer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appbascer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

appbascer/app/views/registro_de_residuos/_form.html.erb
<%= form_with(model: registro_de_residuo, local: true) do |form| %>
  <% if registro_de_residuo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registro_de_residuo.errors.count, "error") %> prohibited this registro_de_residuo from being saved:</h2>

      <ul>
      <% registro_de_residuo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :contenedor %>
    <%= form.text_field :contenedor %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

appbascer/app/views/registro_de_residuos/edit.html.erb
<h1>Editing Registro De Residuo</h1>

<%= render 'form', registro_de_residuo: @registro_de_residuo %>

<%= link_to 'Show', @registro_de_residuo %> |
<%= link_to 'Back', registro_de_residuos_path %>

appbascer/app/views/registro_de_residuos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registro De Residuos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Tipo</th>
      <th>Contenedor</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registro_de_residuos.each do |registro_de_residuo| %>
      <tr>
        <td><%= registro_de_residuo.fecha %></td>
        <td><%= registro_de_residuo.tipo %></td>
        <td><%= registro_de_residuo.contenedor %></td>
        <td><%= registro_de_residuo.telefono %></td>
        <td><%= link_to 'Show', registro_de_residuo %></td>
        <td><%= link_to 'Edit', edit_registro_de_residuo_path(registro_de_residuo) %></td>
        <td><%= link_to 'Destroy', registro_de_residuo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registro De Residuo', new_registro_de_residuo_path %>

appbascer/app/views/registro_de_residuos/new.html.erb
<h1>New Registro De Residuo</h1>

<%= render 'form', registro_de_residuo: @registro_de_residuo %>

<%= link_to 'Back', registro_de_residuos_path %>

appbascer/app/views/registro_de_residuos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @registro_de_residuo.fecha %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @registro_de_residuo.tipo %>
</p>

<p>
  <strong>Contenedor:</strong>
  <%= @registro_de_residuo.contenedor %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @registro_de_residuo.telefono %>
</p>

<%= link_to 'Edit', edit_registro_de_residuo_path(@registro_de_residuo) %> |
<%= link_to 'Back', registro_de_residuos_path %>

appbascer/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

appbascer/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

appbascer/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

appbascer/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

appbascer/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

appbascer/app/views/welcome/index.html.erb
<h1>Bascer</h1>
    <p>Comunidad que Recicla - Economía Solidaria</p>
        <img src = "/image/background1.jpg">
        <br>
<h5 class="center">Modelo de Reciclaje</h5>
    <p class="light">hay días específicos para deshacernos de cada tipo de residuo y también instrucciones muy precisas sobre cómo debemos hacerlo.Por ejemplo, en casa las botellas de plástico se lavan, se les quita la etiqueta y el tapón y se separan en una bolsa aparte; los tetrapack se lavan y se doblan correctamente para que ocupen el mínimo espacio y la recogida de residuos especiales (cacerolas, paraguas, artículos rotos) también se realiza en días especiales y debe estar perfectamente señalizada con unas etiquetas identificativas.los edificios no tienen cubos de basura, sino un espacio habilitado para que los vecinos dejen ahí las bolsas de residuos según el día y el tipo de recogida, siempre dentro de las horas establecidas.El reciclaje no es una obligación exclusiva en las casas, sino también en la calle. Cada persona es responsable de los residuos que genere, también en la calle</p>
        <img src = "/image/background2.jpg">
        <br>
        <h5 class="center">Economía Solidaria</h5>
        <br>
    <p class="light">“Hoy en día la basura es un producto distinto a como era antes.  No solo es basura, es un negocio“,los dueños de casa y de empresa filtran los desechos: la materia orgánica se separa, el papel se arroja a los contenedores de reciclaje y cualquier objeto que puede ser rescatado y reutilizado se separa.Descuentos por ropa usada, Las sobras de los medicamentos,Hamburguesas por botellas vacías, todo el mundo ordena su basura. Los hogares separan sus periódicos, plásticos, metal, vidrio, pilas, bombillas y cartón. De esta manera creativa en alianzas estrategicas por sector será posible obtener bonos sociales de ayuda para los emigrantes y otras situaciones además de acumular puntos para el encuentro con los campesinos en plazas de mercado y realizar un trueque que beneficie mutuamente. </p>
    <br>
    <img src = "/image/background3.jpg">
<h5 class="center">Bascer App</h5>
    <br>
  <p class="light">El buen hábito de seleccionar los residuos día a día, clasificarlos ( vidrio, plástico, chatarra, organicos e inorganicos, peligrosos, aluminio, papel, cartón), es la tarea de generar el correcto reciclamiento de materias primas. Alianza con la app del Ministerio del medio ambiente acerca del reciclaje, Incentivar actividad de reciclaje a partir de la adecuada selección, limpieza, secado y deposito en los contenedores acumulando puntos, Formas informativas y desarrollo para redimir puntos en alianzas estratégicas con actividades en panaderías, plazas de mercado y bonos sociales (bocado para el emigrante), y otros.
</p